---
title: "ISL Chapter 4.6 Lab: <br>Logistic Regression, LDA, QDA, and KNN"
author: "Momoko Price"
date: "04/05/2020"
output: 
  html_document:
    css: ch4.css
---

```{r default_setup, include=FALSE}
knitr::opts_chunk$set(include = T,
                      echo = F, 
                      message = F, 
                      warning = F,
                      fig.align = 'left',
                      out.width = '80%')

# global options
options(stringsAsFactors = F)
# Load libraries
require(tidyverse)
require(data.table)
require(ggplot2)
require(gridExtra)
require(PerformanceAnalytics)
require(magrittr)
```

```{r extras, echo=F}
# load custom libraries
require(ISLR)
require(MASS)
```

```{r data, echo=F}
# load data
data(Smarket)
```

##### Step 1: Check data structure & quality
```{r check_data, include=F}
# check structure
str(Smarket)
# check max/min & quantiles of each variable
summary(Smarket)
# facet the variables against one another & look for trends
pairs(Smarket)
# check for correlations (remove 'Direction' var bc it's qualitative)
cor(Smarket[,-9])

```

``` {r save_plots1, include=F}
# save larger version of plots to images folder
png(filename="images/check_data_pairs.png", width = 1900, height = 1024)
pairs(Smarket)
dev.off()
```

``` {r sort_gather, echo=F}
# convert to dataframe
corr <- as.data.frame(cor(Smarket[,-9]))
# turn rownames into a variable
setDT(corr, keep.rownames = "var1")
# gather corrs into single column
corr_tidy <- corr %>% 
  pivot_longer(c(2:9), names_to = "var2", values_to = "corr") %>% 
  # remove self-correlations
  filter(corr != 1) %>%
  # sort from highest to lowest
  arrange(desc(corr))
# remove even rows (duplicates)
toDelete <- seq(1, nrow(corr_tidy), 2)
corrs <- corr_tidy[-toDelete, ]
head(corrs, 9)
```
